[versions]
retrofit2 = "2.9.0"
okhttp3 = "4.11.0"
sandwich = "1.3.9"

[libraries]
# Retrofit2
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit2" }

# OkHttp3
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }

# External Libraries
sandwich = { module = "com.github.skydoves:sandwich", version.ref = "sandwich" }
